### ISSUE TITLE
Your name in the settings page 

### ISSUE THREAD

**Issue by kitsunet** [rdohms/pronto#22]
The option screen states that I am logged in as Rafael Dohms after authenticating via symposiumapp.com. And no, I didn't hack your account ;)

Just checked, seems it's hardcoded here:
https://github.com/rdohms/pronto/blob/master/src/html/options.html#L17

**Comment by rdohms** [comment]
Oh good catch, indeed `<p>You are currently logged in as <span id="info-fullname">Rafael Dohms</span></p>` :p

Let me get on fixing that.
