### ISSUE TITLE
When I register for the phpday CfP, I can not use Pronto! to fill the bio

### ISSUE THREAD

**Issue by skoop** [rdohms/pronto#32]
![google chromescreensnapz022](https://cloud.githubusercontent.com/assets/90003/10933628/32cddfea-82da-11e5-8430-8730294aaab8.png)

I can not fill the bio field in the phpDay registration form (http://cfp.phpday.it/signup) it seems.

**Comment by asgrim** [comment]
I had this issue too

**Comment by skoop** [comment]
@asgrim: sure, but you're not a patron of @rdohms on patreon.com, so he won't be fixing it for you, just for me ;)

**Comment by rdohms** [comment]
Yes, this will be on the 0.4.skoop release :P
