### ISSUE TITLE
Don't show archived talks on Pronto

### ISSUE THREAD

**Issue by asgrim** [rdohms/pronto#43]
tightenco/symposium#126 feature has been implemented in tightenco/symposium#179, which gives the ability to archive a talk.

It would be great if Pronto did not show archived talks, or had the ability to hide archived talks at least.

Thanks <3 :)

**Comment by rdohms** [comment]
so currently the API simply lists all talks, no filter, looking into how to get this data from the endpoint without having to manually filter on our side.

**Comment by rdohms** [comment]
This has been fixed on the API end of Symposium on tightenco/symposium#202
