### ISSUE TITLE
How to log in?

### ISSUE THREAD

**Issue by TomasVotruba** [rdohms/pronto#45]
Hey, thanks for the great tool. Can't wait to try it.

I can't find a working way to connect. What were my steps so far?

- I've registered to Symposium, completed my bio and talks and picked a slug.
- I've installed Pronto on Chrome on Ubuntu 18.04 and tried to log-in. But not sure how exactly that works.

![fail](https://user-images.githubusercontent.com/924196/39406912-a0397396-4bbe-11e8-8fa6-452ce1a0a66d.gif)

I don't use custom Symposium install, so I guessed I shall not completely any of these 3 inputs (I tried various name/password/slug combinations though, with no success)

Am I doing something wrong? 

Thanks for the help

**Comment by rdohms** [comment]
@TomasVotruba when you click on Login a new popup should open where you can fill login at symposium. Can you verify you have nothing blocking that window?

**Comment by TomasVotruba** [comment]
Thanks for reaching out!

I disabled ad-block and I check for any extension configuration in the top bar, but I don't see anything.

Any specific place I should check in Chrome's setting?

**Comment by donis** [comment]
Happens here also, just tried this today 🤔

**Comment by rdohms** [comment]
Yep, just confirmed that if I log out I can't get back in. 
I'm gonna see if i can figure it out, chrome must have changed something in their Oauth API.

**Comment by rdohms** [comment]
Notes to self:
- console hints at `Uncaught TypeError: Cannot read property 'attributes' of undefined` which is used to read the `attributes` property of `/me` symposium response, need to validate that with @mattstauffer but have a feeling its a white rabbit.

**Comment by TomasVotruba** [comment]
Thanks for looking into this

**Comment by rdohms** [comment]
Alright found the problem. Its on Symposium's side and is fixed by tightenco/symposium#234. Once its live i'll mark this issue as solved after testing it.

**Comment by rdohms** [comment]
Symposium update is live and I can login once more.

@TomasVotruba thanks for reporting this, please re-open issue if you still have problems.

**Comment by TomasVotruba** [comment]
Thanks, that was super fast!
